# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-17 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190217_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1'),
        ),
    ]
