# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-17 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesorg',
            old_name='click',
            new_name='click_nums',
        ),
    ]
