# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190220_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesorg',
            name='image',
            field=models.ImageField(default=None, upload_to='org/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
