# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_coursesorg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesorg',
            name='image',
            field=models.ImageField(default=None, upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
