# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20190221_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=None, upload_to='teacher/%Y/%m', verbose_name='logo'),
        ),
    ]
