# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20190222_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesorg',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='\u6a19\u7c3d'),
        ),
    ]
