# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-22 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CoursesOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u6559\u5b66\u8001\u5e08'),
        ),
    ]
