# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190225_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
