# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190225_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.CharField(default='', max_length=100, verbose_name='\u5c0f\u8282'),
        ),
    ]
