# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190225_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='type',
        ),
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f\uff08\u5206\u949f\uff09'),
        ),
    ]
