# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20190225_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youneed_konw',
            field=models.CharField(default='', max_length=100, verbose_name='\u987b\u77e5'),
        ),
    ]
