# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_youneed_konw'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=100, verbose_name='\u987b\u77e5'),
        ),
    ]
