# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_teacher_tell'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresourse',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=100, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
    ]
