# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20190225_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresourse',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
    ]
